baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Data Science South'
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.highlight]
    lineNos = false
    noClasses = false
    lineNumbersInTable = true
    tabWidth = 4
    guessSyntax = false

[taxonomies]
  competency = "competencies"

[params]
  mainSections = ["lessons"]
  math = true



