baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Data Science South'
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    noClasses = false
    lineNumbersInTable = true
    tabWidth = 4

[params]
  mainSections = ["lessons"]
